version: '3'
services:

  lb:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        aliases:
          - lb.local

  apache:
    image: httpd:latest
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      default:
        aliases:
          - apache.local
    depends_on:
      - app
      - lb

  app:
    build:
      context: app
    image: app:latest
    networks:
      default:
        aliases:
          - app.local
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      default:
        aliases:
          - redis.local

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      default:
        aliases:
          - logstash.local

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    networks:
      default:
        aliases:
          - es.local

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    networks:
      default:
        aliases:
          - kibana.local
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es.local:9200
