version: '3'
services:

  lb:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        aliases:
          - lb.local

  apache:
    image: httpd:latest
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      default:
        aliases:
          - apache.local
    depends_on:
      - app
      - lb

  app:
    build:
      context: app
    image: app:latest
    networks:
      default:
        aliases:
          - app.local
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      default:
        aliases:
          - redis.local
